name: CI

on: push

jobs:
  lint:
    name: Lint test
    runs-on: ubuntu-latest

    env:
      PYTHON: '3.10'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true

  test:
    name: unittest
    runs-on: ubuntu-latest

    env:
      PYTHON: '3.10'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f less_2/requirements.txt ]; then pip install -r less_2/requirements.txt; fi
        
      - name: Coverage and Publish
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          coverageCommand: pytest --cov-config=.coveragerc --cov=. less_2 --cov-report xml --cov-report term-missing:skip-covered
          coverageLocations: ${{github.workspace}}/coverage.xml:coverage.py          
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}